### ISSUE TITLE
\menu{} is broken when using babel with spanish

### ISSUE THREAD

**Issue by Noitaenola** [tweh/menukeys#62] opened 2020-11-27 04:30 UTC
Here is a MWE:
```
\documentclass{article}
\usepackage{menukeys}
\usepackage[spanish]{babel}

\begin{document}
	\menu{Extras > Settings > Rulers}
\end{document}
```

This is the result:
![menu](https://user-images.githubusercontent.com/20274082/100410469-9a0b9f00-304d-11eb-9efa-ec3752478436.png)

Removing the `spanish` option yields the correct result. It works OK with `german` and `french`, at least. Adding `\usepackage[T1]{fontenc}` before `menukeys` changes the inverted quotation marks for `>`. `\keys{}` and `\directory{}` are not affected.

I'm running MikTeX under Win10.

**Comment by tweh** [comment] 2020-11-27 08:38
I guess this happens since `>` becomes an active character for `spanish`. The easiest way to solve this is to use another operator for menus.

```latex
\documentclass{article}
\usepackage{menukeys}
\usepackage[spanish]{babel}

\renewmenumacro{\menu}[+]{menus}

\begin{document}
	\menu{Extras + Settings + Rulers}
\end{document}
```

**Comment by Skillmon** [comment] 2020-11-27 20:21
Indeed, this is because the `>` is active. Another problem is, that the current code doesn't work for active characters as separators (as a result of the way the `\tw@default@input@sep` is currently handled). I could fix that in the current code version. Afterwards the following should work as well:

```
\documentclass{article}
\usepackage{menukeys}
\usepackage[spanish]{babel}

\begin{document}
\renewmenumacro{\menu}[>]{menus}
\menu{Extras > Settings > Rulers}
\end{document}
```

**Comment by Noitaenola** [comment] 2020-11-27 20:53
Thank you both for your prompt replies. It would be great if the quirk could be fixed in-package, but the workaround is good enough for me. Feel free to close the issue.

**Comment by Skillmon** [comment] 2020-11-28 12:01
I'd like to keep this open for now as a reminder that this should be fixed.

@tweh Maybe we should fix a few things in the current version before a big rewrite. I'd have two things in mind:

1. use `\regex_split:nnN` instead of `\seq_set_split:Nnn`, this way we could allow different category codes to be handled correctly (I think this was the case with the `catoptions` solution), but it could require some sanitising, I'd have to test a few things.

2. change the way `\tw@default@input@sep` is handled, as it currently requires the function to expand the delimiter once, which can go horribly wrong for active tokens or macros as delimiters.

The second is a rather easy change, the following would do:

```latex
\NewDocumentCommand{\newmenumacro}{m o m}{%
   \ifcsundef{\expandafter\@gobble\string#1}{%
      \IfNoValueTF{#2}
        {\exp_args:NNno\tw@define@menu@macro\NewDocumentCommand{#1}{\tw@default@input@sep}{#3}}
        {\tw@define@menu@macro\NewDocumentCommand{#1}{#2}{#3}}%
   }{%
      \tw@mk@error{Menu macro '\string#1' already defined!\MessageBreak
      Use \string\renewmenustyle\space instead.}%
   }%
}
```

and the similar changes to `\renewmenumacro` and `\providemenumacro`. This way `\tw@mk@indrisloop` doesn't have to expand its second argument. Or we just drop the usage of `\tw@default@input@sep` and use a comma directly in the optional argument.

**Closed** 2020-11-28 16:43 UTC

**Comment by Skillmon** [comment] 2020-11-28 16:47
I didn't implement the usage of `\regex_split:nnN` instead of `\seq_set_split:Nnn`, as the syntax of regular expressions would require quite a lot of sanitising on the separator (e.g., `+` would've to be input as `\+`). For simplicity I dropped this idea for now.

Nevertheless I changed the way `\tw@default@input@sep` is handled, so that it isn't `x`-type expanded anymore. Now using `\renewmenumacro` after `\begin{document}` would allow active separators.

**Comment by Noitaenola** [comment] 2020-12-05 03:13
Is there a date for this update to hit CTAN?

**Comment by Skillmon** [comment] 2020-12-05 09:25
@Noitaenola the code is written. I just have to review it and make sure that it doesn't have any regressions. The problem is, that I don't have much free-time currently, but that's going to turn better next week. Definitely before Christmas, but that's all that I can promise.

You can act as a beta-tester, if you want. Just download the .dtx and .ins file from the repository, run `latex menukeys.ins` and put the resulting `menukeys.sty` in your project's working directory. If I didn't screw up, this should then all work. If I did screw something up, you can open a new issue, and I would be grateful :)

One of the problems is, that besides the documentation I don't have any test-cases set up to quickly test for regressions, so making sure everything works takes time.

**Comment by Noitaenola** [comment] 2020-12-08 05:14
I can confirm version 1.6.1 works as expected. Having to add ` \renewmenumacro{\menu}[>]{menus}` **after** `\begin{document}` seems a little awkward but I could learn to live with that :).

Thank you very much for maintaining this fantastic package!

**Comment by Skillmon** [comment] 2020-12-08 12:26
@Noitaenola I could add another option to the package (or make this automatic) that checks for the category codes of the parsing letters at `\begin{document}`, so that this could be automatically handled (but I have to think of a sane interface, such that users can easily overwrite it and that it happens transparently).

The reason why you have to put that after `\begin{document}` is because `babel` turns the characters active at that point and not earlier. You could as well use the following in the preamble, if you prefer that (caution, more complicated):

```latex
\begingroup
\lccode`\~=`\>
\lowercase{\endgroup
  \renewmenumacro{\menu}[>]{menus}%
}
```

**Comment by Noitaenola** [comment] 2020-12-10 04:45
Thanks for the heads-up.

The issue seems rather specific. I wouldn't mind waiting for v2 to see an integral solution implemented, given some simple workarounds already exist.
